### PR TITLE
Streamline container size

### PR DESCRIPTION
**Pull request by jennyfothergill**
Do not merge until https://github.com/openmm/openmm/issues/3059 is resolved, but I will update with fix found there
EDIT: temporary(?) fix

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
Will the remove --force fix be good enough for our purposes?

**Comment by jennyfothergill** [comment]
hmmm... force removing could break our installation. I think waiting until the openmm devs decide on a fix is best. Hopefully they drop the cudatoolkit requirement. :)

**Comment by jaimergp** [comment]
If it's only for a container, `conda remove --force cudatoolkit` should not cause too many troubles. The environment will be deemed "inconsistent" by `conda` and it will try to fix it, but if you don't try to update anything else, it _should_ work as long as there's a CUDA toolkit somewhere in the image. Worth a try, in my opinion!

**Comment by jennyfothergill** [comment]
This solution may be the best:
> For permanent effects, you could change the default channels list in your `~/.condarc` so the `conda-forge/label/nocuda` channel sits above the normal `conda-forge`.

_Originally posted by @jaimergp in https://github.com/openmm/openmm/issues/3059#issuecomment-876556363_

**Comment by jaimergp** [comment]
I'd add that the `nocuda` channel does not exist yet and is still hypothetical!

**Comment by jennyfothergill** [comment]
OH. That's an important distinction I missed.

**Comment by jaimergp** [comment]
Check this comment ;)

https://github.com/openmm/openmm/issues/3059#issuecomment-891653746

**Review by chrisjonesBSU — APPROVED** [review]

**Pull request merged**
